//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Yupi! Private HH Emulator")]
[assembly: System.Reflection.AssemblyDescription("Private Open Source HH Emulator for Cool Guys")]
[assembly: System.Reflection.AssemblyCompany("UIoT")]
[assembly: System.Reflection.AssemblyProduct("Yupi! Emulator")]
[assembly: System.Reflection.AssemblyCopyright("Claudio A. Santoro W., Kessiler R., Sulake Corp. Oy")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("39becc2f4deba222a5d6e8d69e4c80df39ff65b0")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.39becc2")]


